apiVersion: v1
kind: Service

metadata:
  name: apigateway-service
  labels:
    monitoring: nimbus
spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8083
      targetPort: 8083

  type: ClusterIP