apiVersion: v1
kind: Service

metadata:
  name: inventory-service
  labels:
    monitoring: nimbus
spec:
  selector:
    app: inventory-service

  ports:
    - name: http
      port: 8082
      targetPort: 8082

  type: ClusterIP