apiVersion: v1
kind: Service

metadata:
  name: product-service
  labels:
    monitoring: nimbus
spec:
  selector:
    app: product-service

  ports:
    - name: http
      port: 8081
      targetPort: 8081

  type: ClusterIP