apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
          
      containers:
        - name: product-service

          image: "{{ .Values.images.product.repository }}:{{ .Values.images.product.tag }}"

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nimbus-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nimbus-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nimbus-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: nimbus-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nimbus-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
{{ toYaml .Values.resources | indent 12 }}