apiVersion: v1
kind: Secret
metadata:
  name: nimbus-secret

type: Opaque

stringData:
  DB_USER: {{ .Values.postgres.username | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}