apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: nimbus-services-monitor
  labels:
    release: monitoring

spec:

  selector:
    matchLabels:
      monitoring: nimbus

  endpoints:
    - port: http
      path: /metrics
      interval: 15s