name: Nimbus Commerce CI/CD     #WorkflowCI.part

permissions:
  contents: write

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      ####################################################
      # Checkout
      ####################################################
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      ####################################################
      # AWS Credentials
      ####################################################
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      ####################################################
      # Login ECR
      ####################################################
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ####################################################
      # PRODUCT SERVICE
      ####################################################
      - name: Build Product Image
        run: |
          docker build \
            -t nimbus-product:${{ github.sha }} \
            ./services/product-service

      - name: Tag Product Image
        run: |
          docker tag \
          nimbus-product:${{ github.sha }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nimbus-product:${{ github.sha }}

      - name: Push Product Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nimbus-product:${{ github.sha }}

      ####################################################
      # INVENTORY SERVICE
      ####################################################
      - name: Build Inventory Image
        run: |
          docker build \
            -t nimbus-inventory:${{ github.sha }} \
            ./services/inventory-service

      - name: Tag Inventory Image
        run: |
          docker tag \
          nimbus-inventory:${{ github.sha }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nimbus-inventory:${{ github.sha }}

      - name: Push Inventory Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nimbus-inventory:${{ github.sha }}

      ####################################################
      # API GATEWAY
      ####################################################
      - name: Build Gateway Image
        run: |
          docker build \
            -t nimbus-gateway:${{ github.sha }} \
            ./services/api-gateway

      - name: Tag Gateway Image
        run: |
          docker tag \
          nimbus-gateway:${{ github.sha }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nimbus-gateway:${{ github.sha }}

      - name: Push Gateway Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nimbus-gateway:${{ github.sha }}

      ####################################################
      # UPDATE HELM
      ####################################################
      - name: Update Helm Tags
        run: |
          sed -i "s/tag: .*/tag: ${{ github.sha }}/g" helm/nimbus-commerce/values.yaml

      ####################################################
      # COMMIT
      ####################################################
      - name: Commit Helm Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add helm/nimbus-commerce/values.yaml

          git diff --cached --quiet || git commit -m "Update images to ${{ github.sha }}"

      ####################################################
      # PUSH
      ####################################################
      - name: Push Changes
        run: git push